Add support for loading SVG icons using librsvg.
This adds a configure option --disable-librsvg, but defaults to
using the library if it is present during configure.

When enabled, Openbox will attempt to load svg image files using
the library, similar to how Imlib2 is used for other image
formats.

Since librsvg uses the libXml2 library, their errors end up in
the same global namespace as Openbox config file parsing. To
avoid this, we reset the libXml current error whenever we start
loading a file, and save the last error that occurred when we
are finished, by storing the error in the ObtXmlInst.

diff --git a/release/go b/release/go
--- a/release/go
+++ b/release/go
@@ -78,6 +78,13 @@ make >/dev/null 2>/dev/null || \
   error "make (with --disable-imlib2) failed"
 make clean >/dev/null || error "make clean failed"
 
+echo Check compile with librsvg disabled
+./configure -C --disable-imlib2 >/dev/null || \
+  error "configure failed"
+make >/dev/null 2>/dev/null || \
+  error "make (with --disable-librsvg) failed"
+make clean >/dev/null || error "make clean failed"
+
 echo Check compile with session management disabled
 ./configure -C --disable-session-management >/dev/null || \
   error "configure failed"
